// 0x0F000A30
const GeoLayout color_box_geo[] = {
   GEO_CULLING_RADIUS(500),
   GEO_OPEN_NODE(),
      //GEO_ASM(0, geo_update_layer_transparency),
      GEO_SWITCH_CASE(18, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, transparent_box_dl_no_shading),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
