// 0x0F000A30
const GeoLayout color_box_geo[] = {
   GEO_CULLING_RADIUS(500),
   GEO_OPEN_NODE(),
      //GEO_ASM(0, geo_update_layer_transparency),
      GEO_SWITCH_CASE(577, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q4_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e1_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e2_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e3_box_dl_shaded),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e4_box_dl_shaded),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, red_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, orange_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, yellow_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, green_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, lime_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, cyan_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, teal_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, purple_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, magenta_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, pink_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, brown_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, skin_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, black_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, grey_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_OPAQUE, white_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, red_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, orange_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yellow_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, green_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lime_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cyan_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, teal_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, blue_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, purple_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, magenta_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pink_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, brown_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, skin_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, black_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, grey_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_q4_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e1_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e2_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e3_box_dl_no_shading),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e4_box_dl_no_shading),

         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, white_e4_box_dl_no_shading),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
