extern const GeoLayout mce_block_Bone_001_opt1[];
extern const GeoLayout mce_block_Bone_001_opt2[];
extern const GeoLayout mce_block_Bone_001_opt3[];
extern const GeoLayout mce_block_geo[];
extern Lights1 mce_block_f3dlite_material_lights;
extern Lights1 mce_block_f3dlite_material_001_lights;
extern Lights1 mce_block_f3dlite_material_002_lights;
extern Vtx mce_block_Bone_002_mesh_layer_7_vtx_0[24];
extern Gfx mce_block_Bone_002_mesh_layer_7_tri_0[];
extern Gfx mat_mce_block_f3dlite_material[];
extern Gfx mat_revert_mce_block_f3dlite_material[];
extern Gfx mat_mce_block_f3dlite_material_001[];
extern Gfx mat_revert_mce_block_f3dlite_material_001[];
extern Gfx mat_mce_block_f3dlite_material_002[];
extern Gfx mat_revert_mce_block_f3dlite_material_002[];
extern Gfx mce_block_Bone_002_mesh_layer_7[];
extern Gfx mce_block_Bone_002_mesh_layer_7_mat_override_f3dlite_material_0[];
extern Gfx mce_block_Bone_002_mesh_layer_7_mat_override_f3dlite_material_001_1[];
extern Gfx mce_block_Bone_002_mesh_layer_7_mat_override_f3dlite_material_002_2[];
